import uuid from 'uuid';
import { FunctionParameters } from 'amplify-function-plugin-interface';

/**
 * Populates FunctionParameters that do not require any additional input
 * @param context The Amplify Context object
 */
export default function autogeneratedParameters(context: any): Partial<FunctionParameters> {
  const appName = context.amplify
    .getProjectDetails()
    .projectConfig.projectName.toLowerCase()
    .replace(/[^0-9a-zA-Z]/gi, '');
  const [shortId] = uuid().split('-');

  return {
    roleName: `${appName}LambdaRole${shortId}`,
  };
}
