import { v4 as uuid } from 'uuid';
import { FunctionParameters } from '@aws-amplify/amplify-function-plugin-interface';
import { $TSContext } from '@aws-amplify/amplify-cli-core';

/**
 * Populates FunctionParameters that do not require any additional input
 */
export const autoGeneratedParameters = (context: $TSContext): Partial<FunctionParameters> => {
  const appName = context.amplify
    .getProjectDetails()
    .projectConfig.projectName.toLowerCase()
    .replace(/[^0-9a-zA-Z]/gi, '');
  const [shortId] = uuid().split('-');

  return {
    roleName: `${appName}LambdaRole${shortId}`,
  };
};
