import RequestValidator from './requestValidator';
import Deployment from './deployment';
import Authorizer from './authorizer';
import DomainName from './domainName';
import DocumentationPart from './documentationPart';
import ApiKey from './apiKey';
import Model from './model';
import Resource from './resource';
import Account from './account';
import RestApi from './restApi';
import UsagePlan from './usagePlan';
import BasePathMapping from './basePathMapping';
import Stage from './stage';
import VpcLink from './vpcLink';
import GatewayResponse from './gatewayResponse';
import ClientCertificate from './clientCertificate';
import Method from './method';
import DocumentationVersion from './documentationVersion';
import UsagePlanKey from './usagePlanKey';
declare const _default: {
    RequestValidator: typeof RequestValidator;
    Deployment: typeof Deployment;
    Authorizer: typeof Authorizer;
    DomainName: typeof DomainName;
    DocumentationPart: typeof DocumentationPart;
    ApiKey: typeof ApiKey;
    Model: typeof Model;
    Resource: typeof Resource;
    Account: typeof Account;
    RestApi: typeof RestApi;
    UsagePlan: typeof UsagePlan;
    BasePathMapping: typeof BasePathMapping;
    Stage: typeof Stage;
    VpcLink: typeof VpcLink;
    GatewayResponse: typeof GatewayResponse;
    ClientCertificate: typeof ClientCertificate;
    Method: typeof Method;
    DocumentationVersion: typeof DocumentationVersion;
    UsagePlanKey: typeof UsagePlanKey;
};
export default _default;
