export const OWNER_AUTH_STRATEGY = "owner"
export const DEFAULT_OWNER_FIELD = "owner"
export const DEFAULT_IDENTITY_FIELD = "username"
export const GROUPS_AUTH_STRATEGY = "groups"
export const DEFAULT_GROUPS_FIELD = "groups"
export const ON_CREATE_FIELD = "onCreate"
export const ON_UPDATE_FIELD = "onUpdate"
export const ON_DELETE_FIELD = "onDelete"