export class NotImplementedError extends Error {}
export class ResourceAlreadyExistsError extends Error {}
export class ResourceDoesNotExistError extends Error {}
export class ResourceCredentialsNotFoundError extends Error {}
export class UnknownResourceTypeError extends Error {}
export class UnknownArgumentError extends Error {}
export class EnvironmentDoesNotExistError extends Error {}
export class MissingParametersError extends Error {}
export class NonEmptyDirectoryError extends Error {}
export class InvalidEnvironmentNameError extends Error {}
export class InvalidSubCommandError extends Error {}
export class FrontendBuildError extends Error {}
export class TeamProviderInfoMigrateError extends Error {}
export class AppNotFoundError extends Error {}
export class AppAlreadyDeployedError extends Error {}
export class SchemaDoesNotExistError extends Error {}
