"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.autoGeneratedParameters = void 0;
const uuid_1 = require("uuid");
const autoGeneratedParameters = (context) => {
    const appName = context.amplify
        .getProjectDetails()
        .projectConfig.projectName.toLowerCase()
        .replace(/[^0-9a-zA-Z]/gi, '');
    const [shortId] = (0, uuid_1.v4)().split('-');
    return {
        roleName: `${appName}LambdaRole${shortId}`,
    };
};
exports.autoGeneratedParameters = autoGeneratedParameters;
//# sourceMappingURL=autogeneratedParameters.js.map