import { FunctionParameters } from '@aws-amplify/amplify-function-plugin-interface';
import { $TSContext } from 'amplify-cli-core';
export declare const autoGeneratedParameters: (context: $TSContext) => Partial<FunctionParameters>;
//# sourceMappingURL=autogeneratedParameters.d.ts.map