/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_appsync_graphqlEndpoint: 'https://weifszkik5fvjcl2rwxikeogbm.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-vjhzo23hgzanjaps65yuddxwqm',
  aws_cognito_identity_pool_id: 'us-east-1:4370716c-e0de-4e67-8309-605ac1212d7b',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_DQBdzEhtg',
  aws_user_pools_web_client_id: '14pombbuk9u7o1r6n07le9umf6',
  oauth: {},
  aws_cognito_username_attributes: ['PHONE_NUMBER'],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL', 'PHONE_NUMBER'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_dynamodb_all_tables_region: 'us-east-1',
  aws_dynamodb_table_schemas: [
    {
      tableName: 'activity-main',
      region: 'us-east-1',
    },
  ],
};

export default awsmobile;
