#########################################################################################
# Use the extraction block to define changes to the default code extraction process     #
# for one or more languages. The settings for each language are defined in a child      #
# block, with one or more steps.                                                        #
#########################################################################################

extraction:
  # Define settings for JavaScript analysis
  ##########################################
  javascript:
    # The `index` step extracts information from the files in the codebase.
    index:
      # Specify a list of glob patterns to include/exclude files from extraction; this 
      # is applied on top of the include/exclude paths from above; patterns are 
      # processed in the same way as for path classifiers above.
      # Default: include all files with known extensions (such as .js, .ts and .html),
      # but exclude files ending in `-min.js` or `.min.js` and folders named `node_modules`
      # or `bower_components`
      filters:
        # exclude any *.ts files anywhere.
        - exclude: "packages/amplify-category-api/resources/awscloudformation/container-templates/**/*.js"