cacheFolder: ~/.yarn/berry/cache

compressionLevel: 0

enableGlobalCache: true

logFilters:
  - code: YN0060
    level: discard
  - code: YN0002
    level: discard
  - code: YN0007
    level: discard

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-3.5.0.cjs
