codecov:
  notify:
    after_n_builds: 1

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        if_ci_failed: error
    patch: off
    changes:
      default:
        target: 80%
        if_not_found: success
