import Table from './table';
import Connection from './connection';
import Partition from './partition';
import Job from './job';
import Database from './database';
import DevEndpoint from './devEndpoint';
import Trigger from './trigger';
import Crawler from './crawler';
import Classifier from './classifier';
declare const _default: {
    Table: typeof Table;
    Connection: typeof Connection;
    Partition: typeof Partition;
    Job: typeof Job;
    Database: typeof Database;
    DevEndpoint: typeof DevEndpoint;
    Trigger: typeof Trigger;
    Crawler: typeof Crawler;
    Classifier: typeof Classifier;
};
export default _default;
