export const constants = {
  HELP: 'help',
  HELP_SHORT: 'h',
  VERSION: 'version',
  VERSION_SHORT: 'v',
  VERBOSE: 'verbose',
  YES: 'yes',
  YES_SHORT: 'y',
  PLUGIN_DEFAULT_COMMAND: 'PLUGIN_DEFAULT_COMMAND',
  MANIFEST_FILE_NAME: 'amplify-plugin.json',
  PACKAGEJSON_FILE_NAME: 'package.json',
  PLUGINS_FILE_NAME: 'plugins.json',
  CORE: 'core',
  CODEGEN: 'codegen',
  AMPLIFY: 'amplify',
  DOT_AMPLIFY_DIR_NAME: '.amplify',
  DEFAULT_PROVIDER: 'awscloudformation',
  AMPLIFY_PREFIX: 'amplify-',
  LOCAL_NODE_MODULES: 'cli-local-node-modules',
  PARENT_DIRECTORY: 'cli-parent-directory',
  GLOBAL_NODE_MODULES: 'global-node-modules',
  PACKAGED_NODE_MODULES: 'packaged-node-modules',
  DEV_NODE_MODULES: 'dev-node-modules',
  EXECUTE_AMPLIFY_COMMAND: 'executeAmplifyCommand',
  EXECUTE_AMPLIFY_HEADLESS_COMMAND: 'executeAmplifyHeadlessCommand',
  HANDLE_AMPLIFY_EVENT: 'handleAmplifyEvent',
  LOG_FILENAME: 'amplify-cli.log',
};
