import { Context } from './context';
export declare class AmplifyToolkit {
    private _cleanUpTasks;
    get confirmPrompt(): any;
    get constants(): any;
    get constructExeInfo(): any;
    get copyBatch(): any;
    get crudFlow(): any;
    get deleteProject(): any;
    get executeProviderUtils(): any;
    get getAllEnvs(): any;
    get getPlugin(): any;
    get getCategoryPluginInfo(): any;
    get getAllCategoryPluginInfo(): any;
    get getFrontendPlugins(): any;
    get getProviderPlugins(): any;
    get getEnvDetails(): any;
    get getEnvInfo(): any;
    get getPluginInstance(): any;
    get getProjectConfig(): any;
    get getProjectDetails(): any;
    get getProjectMeta(): any;
    get getResourceStatus(): any;
    get getResourceOutputs(): any;
    get getWhen(): any;
    get inputValidation(): any;
    get listCategories(): any;
    get makeId(): any;
    get openEditor(): any;
    get onCategoryOutputsChange(): any;
    get pathManager(): any;
    get pressEnterToContinue(): any;
    get pushResources(): any;
    get storeCurrentCloudBackend(): any;
    get readJsonFile(): any;
    get removeResource(): any;
    get sharedQuestions(): any;
    get showHelp(): any;
    get showAllHelp(): any;
    get showHelpfulProviderLinks(): any;
    get showResourceTable(): any;
    get showStatusTable(): any;
    get serviceSelectionPrompt(): any;
    get updateProjectConfig(): any;
    get updateamplifyMetaAfterResourceUpdate(): any;
    get updateamplifyMetaAfterResourceAdd(): any;
    get updateamplifyMetaAfterResourceDelete(): any;
    get updateProviderAmplifyMeta(): any;
    get updateamplifyMetaAfterPush(): any;
    get updateamplifyMetaAfterBuild(): any;
    get updateAmplifyMetaAfterPackage(): any;
    get updateBackendConfigAfterResourceAdd(): any;
    get updateBackendConfigAfterResourceUpdate(): any;
    get updateBackendConfigAfterResourceRemove(): any;
    get loadEnvResourceParameters(): any;
    get saveEnvResourceParameters(): any;
    get removeResourceParameters(): any;
    get removeDeploymentSecrets(): any;
    get triggerFlow(): any;
    get addTrigger(): any;
    get updateTrigger(): any;
    get deleteTrigger(): any;
    get deleteAllTriggers(): any;
    get deleteDeselectedTriggers(): any;
    get dependsOnBlock(): any;
    get getTags(): any;
    get getTriggerMetadata(): any;
    get getTriggerPermissions(): any;
    get getTriggerEnvVariables(): any;
    get getTriggerEnvInputs(): any;
    get getUserPoolGroupList(): any;
    get forceRemoveResource(): any;
    get writeObjectAsJson(): any;
    get hashDir(): any;
    get leaveBreadcrumbs(): any;
    get readBreadcrumbs(): any;
    get loadRuntimePlugin(): any;
    get getImportedAuthProperties(): any;
    get invokePluginMethod(): any;
    constructor();
    addCleanUpTask: (task: (context: Context) => void) => void;
    runCleanUpTasks: (context: Context) => Promise<void>;
}
//# sourceMappingURL=amplify-toolkit.d.ts.map