export const constants = {
  HELP: 'help',
  HELP_SHORT: 'h',
  VERSION: 'version',
  VERSION_SHORT: 'v',
  YES: 'yes',
  YES_SHORT: 'y',
  PLUGIN_DEFAULT_COMMAND: 'PLUGIN_DEFAULT_COMMAND',
  MANIFEST_FILE_NAME: 'amplify-plugin.json',
  PACKAGEJSON_FILE_NAME: 'package.json',
  PLUGINS_FILE_NAME: 'plugins.json',
  CORE: 'core',
  Amplify: 'amplify',
  DotAmplifyDirName: '.amplify',
  AmplifyPrefix: 'amplify-',
  LocalNodeModules: 'cli-local-node-modules',
  ParentDirectory: 'cli-parent-directory',
  GlobalNodeModules: 'global-node-modules',
  ExecuteAmplifyCommand: 'executeAmplifyCommand',
  HandleAmplifyEvent: 'handleAmplifyEvent',
};
