import RouteTable from './routeTable';
import VPCPeeringConnection from './vpcPeeringConnection';
import PlacementGroup from './placementGroup';
import NetworkAclEntry from './networkAclEntry';
import InternetGateway from './internetGateway';
import LaunchTemplate from './launchTemplate';
import Volume from './volume';
import SpotFleet from './spotFleet';
import VPNConnectionRoute from './vpnConnectionRoute';
import NetworkInterfacePermission from './networkInterfacePermission';
import EIP from './eip';
import SecurityGroupIngress from './securityGroupIngress';
import SubnetRouteTableAssociation from './subnetRouteTableAssociation';
import Route from './route';
import FlowLog from './flowLog';
import SecurityGroupEgress from './securityGroupEgress';
import NetworkInterface from './networkInterface';
import SubnetNetworkAclAssociation from './subnetNetworkAclAssociation';
import SubnetCidrBlock from './subnetCidrBlock';
import NatGateway from './natGateway';
import SecurityGroup from './securityGroup';
import Subnet from './subnet';
import VPC from './vpc';
import Instance from './instance';
import DHCPOptions from './dhcpOptions';
import NetworkAcl from './networkAcl';
import VPNGatewayRoutePropagation from './vpnGatewayRoutePropagation';
import EgressOnlyInternetGateway from './egressOnlyInternetGateway';
import NetworkInterfaceAttachment from './networkInterfaceAttachment';
import CustomerGateway from './customerGateway';
import TrunkInterfaceAssociation from './trunkInterfaceAssociation';
import VolumeAttachment from './volumeAttachment';
import Host from './host';
import EIPAssociation from './eipAssociation';
import VPNGateway from './vpnGateway';
import VPCEndpoint from './vpcEndpoint';
import VPCGatewayAttachment from './vpcGatewayAttachment';
import VPNConnection from './vpnConnection';
import VPCCidrBlock from './vpcCidrBlock';
import VPCDHCPOptionsAssociation from './vpcdhcpOptionsAssociation';
declare const _default: {
    RouteTable: typeof RouteTable;
    VPCPeeringConnection: typeof VPCPeeringConnection;
    PlacementGroup: typeof PlacementGroup;
    NetworkAclEntry: typeof NetworkAclEntry;
    InternetGateway: typeof InternetGateway;
    LaunchTemplate: typeof LaunchTemplate;
    Volume: typeof Volume;
    SpotFleet: typeof SpotFleet;
    VPNConnectionRoute: typeof VPNConnectionRoute;
    NetworkInterfacePermission: typeof NetworkInterfacePermission;
    EIP: typeof EIP;
    SecurityGroupIngress: typeof SecurityGroupIngress;
    SubnetRouteTableAssociation: typeof SubnetRouteTableAssociation;
    Route: typeof Route;
    FlowLog: typeof FlowLog;
    SecurityGroupEgress: typeof SecurityGroupEgress;
    NetworkInterface: typeof NetworkInterface;
    SubnetNetworkAclAssociation: typeof SubnetNetworkAclAssociation;
    SubnetCidrBlock: typeof SubnetCidrBlock;
    NatGateway: typeof NatGateway;
    SecurityGroup: typeof SecurityGroup;
    Subnet: typeof Subnet;
    VPC: typeof VPC;
    Instance: typeof Instance;
    DHCPOptions: typeof DHCPOptions;
    NetworkAcl: typeof NetworkAcl;
    VPNGatewayRoutePropagation: typeof VPNGatewayRoutePropagation;
    EgressOnlyInternetGateway: typeof EgressOnlyInternetGateway;
    NetworkInterfaceAttachment: typeof NetworkInterfaceAttachment;
    CustomerGateway: typeof CustomerGateway;
    TrunkInterfaceAssociation: typeof TrunkInterfaceAssociation;
    VolumeAttachment: typeof VolumeAttachment;
    Host: typeof Host;
    EIPAssociation: typeof EIPAssociation;
    VPNGateway: typeof VPNGateway;
    VPCEndpoint: typeof VPCEndpoint;
    VPCGatewayAttachment: typeof VPCGatewayAttachment;
    VPNConnection: typeof VPNConnection;
    VPCCidrBlock: typeof VPCCidrBlock;
    VPCDHCPOptionsAssociation: typeof VPCDHCPOptionsAssociation;
};
export default _default;
