/*
  entry code for amplify override root
*/

import { $TSContext, FeatureFlags, generateOverrideSkeleton, pathManager } from 'amplify-cli-core';
import { printer } from 'amplify-prompts';
import * as fs from 'fs-extra';
import * as path from 'path';

const subcommand = 'override';

export const name = 'overrides';

export const run = async (context: $TSContext) => {
  if (FeatureFlags.getBoolean('project.overrides')) {
    const backendDir = pathManager.getBackendDirPath();

    const destPath = path.join(backendDir, 'awscloudformation');
    fs.ensureDirSync(destPath);
    const srcPath = path.join(__dirname, '..', '..', '..', 'resources', 'overrides-resource');
    // removing runtime old root cfn stack
    // no need for rollback since these files will be autogenerated after push
    const oldRootStackFile = path.join(destPath, 'nested-cloudformation-stack.yml');
    if (fs.existsSync(oldRootStackFile)) {
      fs.unlinkSync(oldRootStackFile);
    }
    await generateOverrideSkeleton(context, srcPath, destPath);
  } else {
    printer.info('Project level overrides is currently not turned on. In cli.json file please include the following:');
    printer.info(
      JSON.stringify(
        {
          project: {
            overrides: true,
          },
        },
        undefined,
        2,
      ),
    );
  }
};
