/*
    entry code for amplify override root
*/

import path from 'path';
import { generateOverrideSkeleton, $TSContext, FeatureFlags } from 'amplify-cli-core';
import { printer } from 'amplify-prompts';
import * as fs from 'fs-extra';

const subcommand = 'override';

export const name = 'overrides';

export const run = async (context: $TSContext) => {
  if (FeatureFlags.getBoolean('overrides.project')) {
    const backendDir = context.amplify.pathManager.getBackendDirPath();

    const destPath = path.normalize(path.join(backendDir, 'awscloudformation'));
    const srcPath = path.normalize(path.join(__dirname, '..', '..', '..', 'resources', 'overrides-resource'));
    // empty build dir for old CFN files
    // no need for rollback since these files will be autogenerated after push
    const rootStackBuildPath = path.join(destPath, 'build');
    if (fs.existsSync(rootStackBuildPath)) {
      fs.emptyDirSync(rootStackBuildPath);
    }
    await generateOverrideSkeleton(context, srcPath, destPath);
  } else {
    printer.info('Overrides are not enabled for Root stack . Turn overrides.project = true in cli.json');
  }
};
