name: Bug report
description: Create a report to help us improve Amplify CLI
title: ""
issue_body: true
body:
- type: markdown
  attributes:
    value: Thanks for taking the time to fill out this bug report! Try to include as much information as you can. 
- type: markdown
  attributes:
    value: For reference, the current version of the Amplify CLI is <img src="https://img.shields.io/npm/v/@aws-amplify/cli.svg" />.
- type: markdown
  attributes:
    value: |
      > **Note**: If your issue is regarding the AWS Amplify Console service, please log it in the [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues).
- type: checkboxes
  attributes:
    label: |
      Before opening, please confirm:
    options:
      - label: I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
        required: true
      - label: I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
        required: true
      - label: I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
        required: true
      - label: I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
        required: true
- type: markdown
  attributes:
    value: |
      ## Environment
- type: input
  attributes:
    label: How did you install the Amplify CLI?
    description: "For example: npm, yarn, curl, etc."
- type: input
  attributes:
    label: If applicable, what version of Node.js are you using?
    description: You can use `node -v` to check the node version on your system.
- type: input
  attributes:
    label: Amplify CLI Version
    placeholder: Run `amplify version` to get the Amplify CLI version
  validations:
    required: true
- type: input
  attributes:
    label: What operating system are you using?
    description: "For example: Mac, Windows, Ubuntu."
  validations:
    required: true
- type: dropdown
  attributes:
    label: Amplify Categories
    description: What [Amplify categories](https://github.com/aws-amplify/amplify-cli#category-specific-commands) are being used?
    multiple: true
    options:
      - auth
      - storage
      - function
      - api
      - analytics
      - hosting
      - notifications
      - interactions
      - predictions
      - xr
      - Not applicable
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      ## Details
- type: dropdown
  attributes:
    label: Amplify Commands
    description: If applicable, what Amplify CLI commands (`amplify ...`) are surfacing the issue?
    multiple: true
    options:
      - add
      - codegen
      - configure
      - configure project
      - delete
      - env
      - init
      - publish
      - pull
      - push
      - serve
      - status
      - update
      - Not applicable
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is. Markdown formatting supported.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen. Markdown formatting supported.
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction steps
    description: | 
      How do you trigger this bug? Please walk us through it step by step. 
      Screenshots can be provided in the issue body below. Markdown formatting supported.
    placeholder: |
      1. 
      2.
      3.
      ...
  validations:
    required: true
- type: textarea
  attributes:
    label: GraphQL schema(s)
    description: |
      If applicable, please include your GraphQL schema(s). 

      **Be sure to remove any sensitive data.** 
    value: |
      <details>
      
      ```graphql
      # Put schemas below this line


      ```

      </details>
- type: textarea
  attributes:
    label: Log output
    description: |
      For example, error messages, or stack traces.

      Include any relevant log output under:
      
      ```
      ~/.amplify/logs/amplify-cli-<issue-date>.log
      ```

      **Be sure to remove any sensitive data.** 
      
    value: |
      <details>
      
      ```
      # Put your logs below this line


      ```

      </details>
- type: markdown
  attributes:
    value: |
      ## Additional information
- type: markdown
  attributes:
    value: >
      If you have any additional information, workarounds, etc. for us, use the field below.
      Please note, you can attach screenshots or screen recordings here, by
      dragging and dropping files in the field below.

