---
version: 0.2
batch:
  fast-fail: true
  build-graph:
    - identifier: prepare_build
      buildspec: codebuild_specs/prepare_build.yml
      debug-session: true
      env:
        compute-type: BUILD_GENERAL1_LARGE
        variables:
          IS_AMPLIFY_CI: true
    - identifier: mock_e2e_tests
      buildspec: codebuild_specs/mock_e2e_tests.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
        variables:
          IS_AMPLIFY_CI: true
      depend-on: prepare_build
    - identifier: test
      buildspec: codebuild_specs/test.yml
      debug-session: true
      env:
        compute-type: BUILD_GENERAL1_LARGE
        variables:
          IS_AMPLIFY_CI: true
      depend-on: prepare_build
    - identifier: lint
      buildspec: codebuild_specs/lint.yml
      debug-session: true
      env:
        compute-type: BUILD_GENERAL1_LARGE
        variables:
          IS_AMPLIFY_CI: true
      depend-on:
        - prepare_build
