---
version: 0.2
batch:
  fast-fail: false
  build-graph:
    - identifier: prepare_build
      buildspec: codebuild_specs/prepare_build.yml
      debug-session: true
      env:
        compute-type: BUILD_GENERAL1_LARGE
        variables:
          IS_AMPLIFY_CI: true
    - identifier: cleanup_e2e_resources
      buildspec: codebuild_specs/cleanup_e2e_resources.yml
      debug-session: true
      env:
        compute-type: BUILD_GENERAL1_LARGE
        variables:
          IS_AMPLIFY_CI: true
      depend-on:
        - prepare_build
    - identifier: mock_e2e_tests
      buildspec: codebuild_specs/mock_e2e_tests.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
        variables:
          IS_AMPLIFY_CI: true
      depend-on:
        - prepare_build
    - identifier: test
      buildspec: codebuild_specs/test.yml
      debug-session: true
      env:
        compute-type: BUILD_GENERAL1_LARGE
        variables:
          IS_AMPLIFY_CI: true
      depend-on:
        - prepare_build
    - identifier: lint
      buildspec: codebuild_specs/lint.yml
      debug-session: true
      env:
        compute-type: BUILD_GENERAL1_LARGE
        variables:
          IS_AMPLIFY_CI: true
      depend-on:
        - prepare_build
    - identifier: validate_cdk_version
      buildspec: codebuild_specs/validate_cdk_version.yml
      debug-session: true
      env:
        compute-type: BUILD_GENERAL1_LARGE
        variables:
          IS_AMPLIFY_CI: true
      depend-on:
        - prepare_build
    - identifier: verify_api_extract
      buildspec: codebuild_specs/verify_api_extract.yml
      debug-session: true
      env:
        compute-type: BUILD_GENERAL1_LARGE
        variables:
          IS_AMPLIFY_CI: true
      depend-on:
        - prepare_build
    - identifier: verify_yarn_lock
      buildspec: codebuild_specs/verify_yarn_lock.yml
      debug-session: true
      env:
        compute-type: BUILD_GENERAL1_LARGE
        variables:
          IS_AMPLIFY_CI: true
      depend-on:
        - prepare_build
