---
version: 0.2
batch:
  fast-fail: true
  build-graph:
    - identifier: prepare_build
      buildspec: codebuild_specs/prepare_build.yml
    - identifier: validate_packages
      buildspec: codebuild_specs/validate_packages.yml
      depend-on:
        - prepare_build
