version: 0.2
env:
  shell: bash
  compute-type: BUILD_GENERAL1_MEDIUM
  variables:
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
    CDK_DEFAULT_REGION: us-east-1
    CLI_REGION: us-east-1
    TEST_SUITE: src/__tests__/auth_2b.test.ts
    AMPLIFY_DIR: '$CODEBUILD_SRC_DIR/out'
    AMPLIFY_PATH: '$CODEBUILD_SRC_DIR/out/amplify-pkg-linux-x64'

batch:
  fast-fail: false
  build-graph:
    - identifier: build_linux
      buildspec: codebuild_specs/build_linux.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
    - identifier: build_windows
      buildspec: codebuild_specs/build_windows.yml
      env:
        type: WINDOWS_SERVER_2019_CONTAINER
        compute-type: BUILD_GENERAL1_LARGE
        image: aws/codebuild/windows-base:2019-2.0
    - identifier: test
      buildspec: codebuild_specs/test.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
      depend-on:
        - build_linux
    - identifier: integration_test
      buildspec: codebuild_specs/integration_test.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
      debug-session: true
      depend-on:
        - build_linux
    - identifier: mock_e2e_tests
      buildspec: codebuild_specs/mock_e2e_tests.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
      depend-on:
        - build_linux
    - identifier: validate_cdk_version
      buildspec: codebuild_specs/validate_cdk_version.yml
      depend-on:
        - build_linux
    - identifier: verify_api_extract
      buildspec: codebuild_specs/verify_api_extract.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
      depend-on:
        - build_linux
    - identifier: verify_yarn_lock
      buildspec: codebuild_specs/verify_yarn_lock.yml
      depend-on:
        - build_linux
    - identifier: publish_to_local_registry
      buildspec: codebuild_specs/publish_to_local_registry.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
      depend-on:
        - build_linux
    - identifier: build_pkg_binaries_arm
      buildspec: codebuild_specs/build_pkg_binaries_arm.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
      depend-on:
        - publish_to_local_registry
    - identifier: build_pkg_binaries_linux
      buildspec: codebuild_specs/build_pkg_binaries_linux.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
      depend-on:
        - publish_to_local_registry
    - identifier: build_pkg_binaries_macos
      buildspec: codebuild_specs/build_pkg_binaries_macos.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
      depend-on:
        - publish_to_local_registry
    - identifier: build_pkg_binaries_win
      buildspec: codebuild_specs/build_pkg_binaries_win.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
      depend-on:
        - publish_to_local_registry
    - identifier: upload_pkg_binaries
      buildspec: codebuild_specs/upload_pkg_binaries.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
      depend-on:
        - build_pkg_binaries_arm
        - build_pkg_binaries_linux
        - build_pkg_binaries_macos
        - build_pkg_binaries_win
    - identifier: verify_versions_match
      buildspec: codebuild_specs/verify_versions_match.yml
      depend-on:
        - publish_to_local_registry
    - identifier: run_e2e_tests_linux
      buildspec: codebuild_specs/run_e2e_tests_linux.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
      debug-session: true
      depend-on:
        - upload_pkg_binaries
    - identifier: run_e2e_tests_windows
      buildspec: codebuild_specs/run_e2e_tests_windows.yml
      env:
        type: WINDOWS_SERVER_2019_CONTAINER
        compute-type: BUILD_GENERAL1_LARGE
        image: aws/codebuild/windows-base:2019-2.0
      depend-on:
        - upload_pkg_binaries
