version: 0.2
env:
  shell: bash
  compute-type: BUILD_GENERAL1_MEDIUM
  imagePullCredentialsType: SERVICE_ROLE
  variables:
    CLI_REGION: us-east-1
    TEST_SUITE: src/__tests__/auth_2b.test.ts
    AMPLIFY_DIR: '$CODEBUILD_SRC_DIR/out'
    AMPLIFY_PATH: '$CODEBUILD_SRC_DIR/out/amplify-pkg-linux-x64'
  # secrets-manager:
  #   S3_ACCESS_KEY: "secretname" # s3_access_key in secret manager

batch:
  fast-fail: true
  build-graph:
    - identifier: build_linux
      buildspec: codebuild_specs/build_linux.yml
      debug-session: true
      env:
        compute-type: BUILD_GENERAL1_LARGE
        variables:
          IS_AMPLIFY_CI: true
    - identifier: test
      buildspec: codebuild_specs/test.yml
      debug-session: true
      env:
        compute-type: BUILD_GENERAL1_LARGE
        variables:
          EXAMPLE_SAMPLE: 'test'
      depend-on:
        - build_linux
    - identifier: validate-cdk-version
      buildspec: codebuild_specs/validate-cdk-version.yml
      debug-session: true
      depend-on:
        - build_linux
    # - identifier: verify-api-extract
    #   buildspec: codebuild_specs/verify-api-extract.yml
    #   debug-session: true
    #   env:
    #     compute-type: BUILD_GENERAL1_LARGE
    #   depend-on:
    #     - build_linux
    # - identifier: verify-yarn-lock
    #   buildspec: codebuild_specs/verify-yarn-lock.yml
    #   debug-session: true
    #   depend-on:
    #     - build_linux
    # - identifier: publish_to_local_registry
    #   buildspec: codebuild_specs/publish_to_local_registry.yml
    #   debug-session: true
    #   env:
    #     compute-type: BUILD_GENERAL1_LARGE
    #   depend-on:
    #     - build_linux
    # - identifier: build_pkg_binaries_linux
    #   buildspec: codebuild_specs/build_pkg_binaries_linux.yml
    #   debug-session: true
    #   env:
    #     compute-type: BUILD_GENERAL1_LARGE
    #   depend-on:
    #     - publish_to_local_registry
    # - identifier: run-e2e-tests
    #   buildspec: codebuild_specs/run-e2e-tests.yml
    #   debug-session: true
    #   env:
    #     compute-type: BUILD_GENERAL1_LARGE
    #   depend-on:
    #     - build_pkg_binaries_linux
