version: 0.2
env:
  shell: bash
  imagePullCredentialsType: SERVICE_ROLE
  variables:
    CLI_REGION: us-east-1
    TEST_SUITE: src/__tests__/auth_2b.test.ts
    AMPLIFY_DIR: '$CODEBUILD_SRC_DIR/out'
    AMPLIFY_PATH: '$CODEBUILD_SRC_DIR/out/amplify-pkg-linux-x64'
  # secrets-manager:
  #   S3_ACCESS_KEY: "secretname" # s3_access_key in secret manager

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - source shared-scripts.sh
  build:
    commands:
      - _buildLinux
      # - _publishToLocalRegistry
      # - _buildBinaries
      # - _uploadPkgBinaries
      # - _runE2ETestsLinux
# batch:
#   fast-fail: true
#   build-graph:
#     - identifier: prepare_build
#       buildspec: codebuild_specs/prepare_build.yml
#       debug-session: true
#       env:
#         compute-type: BUILD_GENERAL1_LARGE
#         variables:
#           IS_AMPLIFY_CI: true
#     - identifier: validate_packages
#       buildspec: codebuild_specs/validate_packages.yml
#       debug-session: true
#       env:
#         variables:
#           EXAMPLE_SAMPLE: 'test'
#       depend-on:
#         - prepare_build
