version: 0.2
env:
  shell: bash
  compute-type: BUILD_GENERAL1_MEDIUM
  imagePullCredentialsType: SERVICE_ROLE
  variables:
    CLI_REGION: us-east-1
    TEST_SUITE: src/__tests__/auth_2b.test.ts
    AMPLIFY_DIR: '$CODEBUILD_SRC_DIR/out'
    AMPLIFY_PATH: '$CODEBUILD_SRC_DIR/out/amplify-pkg-linux-x64'
  # secrets-manager:
  #   S3_ACCESS_KEY: "secretname" # s3_access_key in secret manager

batch:
  fast-fail: false
  build-graph:
    - identifier: build_linux
      buildspec: codebuild_specs/build_linux.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
        variables:
          IS_AMPLIFY_CI: true
    - identifier: test
      buildspec: codebuild_specs/test.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
      depend-on:
        - build_linux
    - identifier: mock_e2e_tests
      buildspec: codebuild_specs/mock_e2e_tests.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
      depend-on:
        - build_linux
    - identifier: validate_cdk_version
      buildspec: codebuild_specs/validate_cdk_version.yml
      depend-on:
        - build_linux
    - identifier: verify_api_extract
      buildspec: codebuild_specs/verify_api_extract.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
      depend-on:
        - build_linux
    - identifier: verify_yarn_lock
      buildspec: codebuild_specs/verify_yarn_lock.yml
      depend-on:
        - build_linux
    - identifier: publish_to_local_registry
      buildspec: codebuild_specs/publish_to_local_registry.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
      depend-on:
        - build_linux
    - identifier: build_pkg_binaries_linux
      buildspec: codebuild_specs/build_pkg_binaries_linux.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
      depend-on:
        - publish_to_local_registry
    - identifier: run_e2e_tests
      buildspec: codebuild_specs/run_e2e_tests.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
      depend-on:
        - build_pkg_binaries_linux
