---
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - yarn install
artifacts:
  files:
    - '**/*'
batch:
  fast-fail: true
  build-graph:
    - identifier: prepare_build
      buildspec: codebuild_specs/prepare_build.yml
    - identifier: validate_packages
      buildspec: codebuild_specs/validate_packages.yml
      depend-on:
        - prepare_build
cache:
  paths:
    - ~/.cache/yarn/**/*
