version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
      - echo "Install phase"
  pre_build:
    commands:
      - npm --version
      - echo 'Pre-Build phase completed!'
  build:
    commands:
      - echo 'Build phase completed!'
batch:
    fast-fail: true
artifacts:
  files:
    - '**/*'
