import { SynthUtils } from '@aws-cdk/assert';
import * as cdk from '@aws-cdk/core';
import { AmplifyRootStack } from '../../root-stack-builder/root-stack-builder';

jest.mock('../../root-stack-builder/stack-synthesizer');

describe('Check RootStack Template', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });
  test('rootstack template generated by constructor', () => {
    const app = new cdk.App();
    let mocksynth: cdk.IStackSynthesizer;
    const stack = new AmplifyRootStack(app, 'rootStack', { synthesizer: mocksynth });
    expect(SynthUtils.toCloudFormation(stack)).toMatchSnapshot();
  });

  test('rootstack template generated by constructor with some parameters', () => {
    const app = new cdk.App();
    let mocksynth: cdk.IStackSynthesizer;
    const stack = new AmplifyRootStack(app, 'rootStack', { synthesizer: mocksynth });

    stack.addCfnParameter(
      {
        type: 'String',
        description: 'Name of the common deployment bucket provided by the parent stack',
        default: 'DeploymentBucket',
      },
      'DeploymentBucketName',
    );

    stack.addCfnParameter(
      {
        type: 'String',
        description: 'Name of the common deployment bucket provided by the parent stack',
        default: 'AuthRoleName',
      },
      'AuthRoleName',
    );

    stack.addCfnParameter(
      {
        type: 'String',
        description: 'Name of the common deployment bucket provided by the parent stack',
        default: 'UnAuthRoleName',
      },
      'UnauthRoleName',
    );
    expect(SynthUtils.toCloudFormation(stack)).toMatchSnapshot();
  });

  test('adding same logicalId parameter should throw error', () => {
    const app = new cdk.App();
    let mocksynth: cdk.IStackSynthesizer;
    const stack = new AmplifyRootStack(app, 'rootStack', { synthesizer: mocksynth });

    stack.addCfnParameter(
      {
        type: 'String',
        description: 'Name of the common deployment bucket provided by the parent stack',
        default: 'AuthRoleName',
      },
      'AuthRoleName',
    );

    expect(() =>
      stack.addCfnParameter(
        {
          type: 'String',
          description: 'Name of the common deployment bucket provided by the parent stack',
          default: 'AuthRoleName',
        },
        'AuthRoleName',
      ),
    ).toThrow('logical Id already Exists');
  });

  test(' adding two resources with same logicalId throw error', () => {
    const app = new cdk.App();
    let mocksynth: cdk.IStackSynthesizer;
    const stack = new AmplifyRootStack(app, 'rootStack', { synthesizer: mocksynth });

    stack.addCfnParameter(
      {
        type: 'String',
        description: 'Name of the common deployment bucket provided by the parent stack',
        default: 'DeploymentBucket',
      },
      'DeploymentBucketName',
    );

    // Add Outputs
    stack.addCfnOutput(
      {
        description: 'CloudFormation provider root stack Region',
        value: cdk.Fn.ref('AWS::Region'),
        exportName: cdk.Fn.sub('${AWS::StackName}-Region'),
      },
      'Region',
    );

    stack.addCfnOutput(
      {
        description: 'CloudFormation provider root stack ID',
        value: cdk.Fn.ref('AWS::StackName'),
        exportName: cdk.Fn.sub('${AWS::StackName}-StackName'),
      },
      'StackName',
    );

    expect(() =>
      stack.addCfnOutput(
        {
          description: 'CloudFormation provider root stack deployment bucket name',
          value: cdk.Fn.ref('DeploymentBucketName'),
          exportName: cdk.Fn.sub('${AWS::StackName}-DeploymentBucketName'),
        },
        'DeploymentBucketName',
      ),
    ).toThrow(`There is already a Construct with name 'DeploymentBucketName' in AmplifyRootStack`);
  });

  test('generates root stack Template', async () => {
    const app = new cdk.App();
    let mocksynth: cdk.IStackSynthesizer;
    const stack = new AmplifyRootStack(app, 'rootStack', { synthesizer: mocksynth });

    stack.addCfnParameter(
      {
        type: 'String',
        description: 'Name of the common deployment bucket provided by the parent stack',
        default: 'DeploymentBucket',
      },
      'DeploymentBucketName',
    );

    stack.addCfnParameter(
      {
        type: 'String',
        description: 'Name of the common deployment bucket provided by the parent stack',
        default: 'AuthRoleName',
      },
      'AuthRoleName',
    );

    stack.addCfnParameter(
      {
        type: 'String',
        description: 'Name of the common deployment bucket provided by the parent stack',
        default: 'UnAuthRoleName',
      },
      'UnauthRoleName',
    );

    // Add Outputs
    stack.addCfnOutput(
      {
        description: 'CloudFormation provider root stack Region',
        value: cdk.Fn.ref('AWS::Region'),
        exportName: cdk.Fn.sub('${AWS::StackName}-Region'),
      },
      'Region',
    );

    stack.addCfnOutput(
      {
        description: 'CloudFormation provider root stack ID',
        value: cdk.Fn.ref('AWS::StackName'),
        exportName: cdk.Fn.sub('${AWS::StackName}-StackName'),
      },
      'StackName',
    );

    stack.addCfnOutput(
      {
        description: 'CloudFormation provider root stack name',
        value: cdk.Fn.ref('AWS::StackId'),
        exportName: cdk.Fn.sub('${AWS::StackName}-StackId'),
      },
      'StackId',
    );

    stack.addCfnOutput(
      {
        value: cdk.Fn.getAtt('AuthRole', 'Arn').toString(),
      },
      'AuthRoleArn',
    );

    stack.addCfnOutput(
      {
        value: cdk.Fn.getAtt('UnauthRole', 'Arn').toString(),
      },
      'UnAuthRoleArn',
    );

    await stack.generateRootStackResources();
    expect(SynthUtils.toCloudFormation(stack)).toMatchSnapshot();
  });
});
