import { addCDKResourceDependency, AmplifyResourceProps } from '@aws-amplify/amplify-category-custom';
import { getProjectInfo } from './helpers/project-info';
import { getVmSandbox } from './helpers/vm-sandbox';
export { AmplifyApiGraphQlResourceStackTemplate } from './types/api/amplify-api-resource-stack-types';
export { AmplifyApiRestResourceStackTemplate, ApigwPathPolicy } from './types/api/types';
export { AmplifyAuthCognitoStackTemplate, AmplifyUserPoolGroupStackTemplate } from './types/auth/types';
export { AmplifyRootStackTemplate } from './types/project/types';
export { AmplifyCDKL1, AmplifyDDBResourceTemplate, AmplifyS3ResourceTemplate } from './types/storage/types';
export { getVmSandbox, getProjectInfo, addCDKResourceDependency as addResourceDependency, AmplifyResourceProps };
export type { AmplifyProjectInfo } from './types';