import PortfolioShare from './portfolioShare';
import TagOptionAssociation from './tagOptionAssociation';
import LaunchTemplateConstraint from './launchTemplateConstraint';
import TagOption from './tagOption';
import PortfolioPrincipalAssociation from './portfolioPrincipalAssociation';
import CloudFormationProvisionedProduct from './cloudFormationProvisionedProduct';
import LaunchRoleConstraint from './launchRoleConstraint';
import CloudFormationProduct from './cloudFormationProduct';
import PortfolioProductAssociation from './portfolioProductAssociation';
import Portfolio from './portfolio';
import AcceptedPortfolioShare from './acceptedPortfolioShare';
import LaunchNotificationConstraint from './launchNotificationConstraint';
declare const _default: {
    PortfolioShare: typeof PortfolioShare;
    TagOptionAssociation: typeof TagOptionAssociation;
    LaunchTemplateConstraint: typeof LaunchTemplateConstraint;
    TagOption: typeof TagOption;
    PortfolioPrincipalAssociation: typeof PortfolioPrincipalAssociation;
    CloudFormationProvisionedProduct: typeof CloudFormationProvisionedProduct;
    LaunchRoleConstraint: typeof LaunchRoleConstraint;
    CloudFormationProduct: typeof CloudFormationProduct;
    PortfolioProductAssociation: typeof PortfolioProductAssociation;
    Portfolio: typeof Portfolio;
    AcceptedPortfolioShare: typeof AcceptedPortfolioShare;
    LaunchNotificationConstraint: typeof LaunchNotificationConstraint;
};
export default _default;
