import { DataProvider, ResourceParameters } from './resourceParams';
import _ from 'lodash';

/**
 * Data structure that represents a Map Resource
 */
export type MapParameters = ResourceParameters & {
    providerContext: ProviderContext; // higher level context around the function
    mapName: string; // name of the map
    mapStyleType: MapStyleType;
    dataProvider: DataProvider;
    isDefaultMap: boolean;
    dependsOn?: MapDependency[]; // resources this map depends on
};

export interface ProviderContext {
    provider: string;
    service: string;
    projectName: string;
}

/**
 * The type of Map styles for Esri data provider
 */
export enum EsriMapStyleType {
    Navigation = "Navigation",
    Streets = "Streets",
    Topographic = "Topographic",
    Canvas = "Canvas"
}

/**
 * The type of Map styles for Here data provider
 */
 export enum HereMapStyleType {
    Berlin = "Berlin"
}

export type MapStyleType = EsriMapStyleType | HereMapStyleType;


/**
 * Designed to be backwards compatible with the old way of representing dependencies as
 * {
 *    category: string
 *    resourceName: string
 *    attributes: string[]
 * }
 * and auto-generating environment variable names based on this info
 * When attributeEnvMap is specified, it can specify a custom environment variable name for a dependency attribute
 * If no mapping is found for an attribute in the map, then it falls back to the autogenerated value
 */
export interface MapDependency {
    category: string; // resource category of the dependency
    resourceName: string; // name of the dependency
    attributes: string[]; // attributes that this function depends on (must be outputs of the dependencies CFN template)
    attributeEnvMap?: { [name: string]: string }; // optional attributes to environment variable names map that will be exposed to the function
}

export function isCompleteMapParams(partial: Partial<MapParameters>): partial is MapParameters {
    const requiredFields = ['providerContext', 'mapName', 'mapStyleType', 'dataProvider', 'accessType', 'isDefaultMap'];
    const missingField = requiredFields.find(field => !_.keys(partial).includes(field));
    return !missingField;
}

export function convertToCompleteMapParams(partial: Partial<MapParameters>): MapParameters {
    if (isCompleteMapParams(partial)) {
        return partial as MapParameters;
    }
    throw new Error('Partial<MapParameters> does not satisfy MapParameters');
}

export function getGeoMapStyle(dataProvider: DataProvider, mapStyleType: MapStyleType) {
    return `Vector${dataProvider}${mapStyleType}`;
}
