import path from 'node:path';
import fs from 'node:fs/promises';
import { Planner } from '../../../_infra/planner';
import { AmplifyMigrationOperation } from '../../../_infra/operation';
import { BackendGenerator } from '../backend.generator';
import { DiscoveredResource, Gen1App } from '../../_infra/gen1-app';
import { TS } from '../../_infra/ts';
import { GeoRenderer } from './geo.renderer';
import { GeoCfnConverter, GeoCodegenResult, GeoServiceName, GeoProviderMetadata } from './geo-cfn-converter';

/**
 * Generates a single geo resource file (Map, PlaceIndex, or GeofenceCollection).
 *
 * Each instance handles one geo sub-resource. The aggregator geo/resource.ts
 * is generated by GeoAggregatorGenerator after all sub-resources are done.
 */
export class GeoGenerator implements Planner {
  private readonly gen1App: Gen1App;
  private readonly outputDir: string;
  private readonly resource: DiscoveredResource;
  private readonly renderer: GeoRenderer;
  private codegenResult: GeoCodegenResult | undefined;

  public constructor(gen1App: Gen1App, outputDir: string, resource: DiscoveredResource) {
    this.gen1App = gen1App;
    this.outputDir = outputDir;
    this.resource = resource;
    this.renderer = new GeoRenderer();
  }

  /** Returns the codegen result after plan() has executed. */
  public getCodegenResult(): GeoCodegenResult | undefined {
    return this.codegenResult;
  }

  public async plan(): Promise<AmplifyMigrationOperation[]> {
    const resourceName = this.resource.resourceName;
    const geoCategory = this.gen1App.meta('geo');
    if (!geoCategory || !geoCategory[resourceName]) return [];

    const meta = geoCategory[resourceName] as { service: string; providerMetadata: GeoProviderMetadata; isDefault?: boolean };
    const service = meta.service as GeoServiceName;
    const geoDir = path.join(this.outputDir, 'amplify', 'geo');

    return [
      {
        resource: this.resource,
        validate: () => undefined,
        describe: async () => [`Generate amplify/geo/${resourceName}/resource.ts`],
        execute: async () => {
          const converter = new GeoCfnConverter(
            this.outputDir,
            async (content, filePath) => {
              await fs.mkdir(path.dirname(filePath), { recursive: true });
              await fs.writeFile(filePath, content, 'utf-8');
            },
            this.gen1App.clients.s3,
            this.gen1App.clients.cloudFormation,
            this.gen1App.rootStackName,
          );

          this.codegenResult = await converter.generateGeoL1Code(resourceName, service, meta.providerMetadata);

          const nodes = this.renderer.render(this.codegenResult);
          const content = TS.printNodes(nodes);

          const resourceDir = path.join(geoDir, resourceName);
          await fs.mkdir(resourceDir, { recursive: true });
          await fs.writeFile(path.join(resourceDir, 'resource.ts'), content, 'utf-8');
        },
      },
    ];
  }
}

/**
 * Generates the top-level geo/resource.ts aggregator that imports all
 * sub-resources and calls backend.addOutput() with geo configuration.
 * Must run after all GeoGenerator instances have executed.
 */
export class GeoAggregatorGenerator implements Planner {
  private readonly backendGenerator: BackendGenerator;
  private readonly outputDir: string;
  private readonly geoGenerators: readonly GeoGenerator[];
  private readonly renderer: GeoRenderer;

  public constructor(backendGenerator: BackendGenerator, outputDir: string, geoGenerators: readonly GeoGenerator[]) {
    this.backendGenerator = backendGenerator;
    this.outputDir = outputDir;
    this.geoGenerators = geoGenerators;
    this.renderer = new GeoRenderer();
  }

  public async plan(): Promise<AmplifyMigrationOperation[]> {
    const geoDir = path.join(this.outputDir, 'amplify', 'geo');

    return [
      {
        validate: () => undefined,
        describe: async () => ['Generate amplify/geo/resource.ts'],
        execute: async () => {
          const results = this.geoGenerators.map((g) => g.getCodegenResult()).filter((r): r is GeoCodegenResult => r !== undefined);

          const nodes = this.renderer.renderAggregator(results);
          const content = TS.printNodes(nodes);

          await fs.mkdir(geoDir, { recursive: true });
          await fs.writeFile(path.join(geoDir, 'resource.ts'), content, 'utf-8');

          this.backendGenerator.addNamespaceImport('geo', './geo/resource');
          this.backendGenerator.addPostDefineStatement(`geo.defineGeo(backend)`);
        },
      },
    ];
  }
}
