"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.writeReadMeFile = void 0;
const fs_extra_1 = __importDefault(require("fs-extra"));
const ReadMeContent = `# Getting Started with Amplify CLI
This directory was generated by [Amplify CLI](https://docs.amplify.aws/cli).

Helpful resources:
- Amplify documentation: https://docs.amplify.aws
- Amplify CLI documentation: https://docs.amplify.aws/cli
- More details on this folder & generated files: https://docs.amplify.aws/cli/reference/files
- Join Amplify's community: https://amplify.aws/community/
`;
function writeReadMeFile(readMeFilePath) {
    fs_extra_1.default.writeFileSync(readMeFilePath, ReadMeContent);
}
exports.writeReadMeFile = writeReadMeFile;
//# sourceMappingURL=docs-manager.js.map