import ApiKey from 'cloudform-types/types/appSync/apiKey'
import GraphQLSchema from 'cloudform-types/types/appSync/graphQlSchema'
import GraphQLApi from 'cloudform-types/types/appSync/graphQlApi'
import Role, { Policy } from 'cloudform-types/types/iam/role'
import { ResourceConstants, ModelResourceIDs } from 'graphql-transformer-common'
import { print } from 'graphql'
import DataSource from 'cloudform-types/types/appSync/dataSource'

import cloudform, { Fn, StringParameter, Refs } from 'cloudform'
import Template from 'cloudform-types/types/template'
import Output from 'cloudform-types/types/output'
import TemplateContext from './RelationalDBSchemaTransformer'
import RelationalDBResolverGenerator from './RelationalDBResolverGenerator'

/**
 * This is the Class responsible for generating and managing the CloudForm template
 * provided a TemplateContext object, which is generated by the RelationalDBSchemaTransformer.
 *
 * It will generate the basic CloudForm template needed for getting the AppSync API and
 * RDS DataSource provisioned. It also allows for adding the CRUDL+Q Resolvers upon need.
 */
export default class RelationalDBTemplateGenerator {
    context: TemplateContext

    constructor(context: TemplateContext) {
        this.context = context
    }

    /**
     * Creates and returns the basic Cloudform template needed for setting
     * up an AppSync API pointing at the RDS DataSource.
     */
    public createTemplate(): Template {
        const schemaString = print(this.context.schemaDoc)

        const template =  {
            AWSTemplateFormatVersion: "2010-09-09",
            Parameters: this.makeParameters(),
            Resources: {
                [ResourceConstants.RESOURCES.APIKeyLogicalID]: this.makeAPIKey(),
                [ResourceConstants.RESOURCES.GraphQLAPILogicalID]: this.makeAPISchema(schemaString),
                [ResourceConstants.RESOURCES.AuthCognitoUserPoolJSClientLogicalID]: this.makeGraphQLApi(),
                ['RelationalDatabaseAccessRole']: this.makeIAMDataSourceRole(),
                //TODO: use ModelResourceIds to provide the IAM service role
                ['RelationalDatabaseDataSource']: this.makeRelationalDataSource('placeholder')
            },
            Outputs: {
                [ResourceConstants.OUTPUTS.GraphQLAPIApiKeyOutput]: this.makeAPIKeyOutput(),
                [ResourceConstants.OUTPUTS.GraphQLAPIEndpointOutput]: this.makeGraphQLApiEndpointOutput(),
                [ResourceConstants.OUTPUTS.GraphQLAPIIdOutput]: this.makeGraphQLApiIdOutput()
            }
        }

        return template
    }

    /**
     * Provided a Cloudform Template, this method adds Resolver Resources to the
     * Template.
     *
     * @param template - the Cloudform template
     */
    public addRelationalResolvers(template: Template) : Template {
        let resolverGenerator = new RelationalDBResolverGenerator(this.context)
        template.Resources = {...template.Resources, ...resolverGenerator.createRelationalResolvers()}
        return template
    }

    /**
     * Provided a Cloudform Template, this method returns the cfn json template as a string
     *
     * @param template - the Cloudform template
     */
    public printCloudformationTemplate(template: Template): string {
        return cloudform(template)
    }

    /**
     *
     * Private Helper Methods for Generating the Necessary CFN Specs for the CFN Template
     *
     */

    /**
     * Creates any Parmaters needed for the CFN Template
     */
    private makeParameters() {
        return {
            [ResourceConstants.PARAMETERS.AppSyncApiName]: new StringParameter({
                Description: 'The name of the AppSync API',
                Default: 'My AppSync API'
            })
        }
    }

    /**
     * Resources
     */

    /**
     * Creates the GraphQL API CFN Spec using API_KEY as the Auth Type
     */
    private makeGraphQLApi(): GraphQLApi {
        return new GraphQLApi ({
            Name: Fn.Ref(ResourceConstants.PARAMETERS.AppSyncApiName),
            AuthenticationType: "API_KEY"
        })
    }

    /**
     * Provided the GraphQL Schema as a string (this should be generated by the RelationalDBSchemaTransformer),
     * it creates the GraphQLSchema CFN spec
     * @param schemaString
     */
    private makeAPISchema(schemaString: string): GraphQLSchema {
        return new GraphQLSchema ({
            ApiId: Fn.GetAtt(ResourceConstants.RESOURCES.GraphQLAPILogicalID, 'ApiId'),
            Definition: schemaString
        })
    }

    /**
     * Creates the API Key CFN Spec for the GraphQL API
     */
    private makeAPIKey(): ApiKey {
        return new ApiKey ({
            ApiId: Fn.GetAtt(ResourceConstants.RESOURCES.GraphQLAPILogicalID, 'ApiId'),
            Description: 'AWS AppSync Api key for your relational database GraphQL API'
        })
    }

    /**
     * Creates the IAM Role CFN Spec to allow AppSync to interact with the RDS cluster
     */
    private makeIAMDataSourceRole(): Role {
        return new Role ({
            AssumeRolePolicyDocument: {
                Version: '2012-10-17',
                Statement: {
                    Effect: 'Allow',
                    Principal: {
                        Service: 'appsync.amazonaws.com'
                    },
                    Action: {
                        'sts': 'AssumeRole'
                    }
                }
            },
            Policies: [new Policy ({
                PolicyName: 'RelationalDatabaseAccessPolicy',
                PolicyDocument: {
                    Version: '2012-10-17',
                    Statement: {
                        Effect: 'Allow',
                        // TODO: Further Scope Down the Permissions once identified
                        Action: {
                            'rds': '*',
                            'rds-data': '*',
                            'secretsmanager': '*'
                        },
                        Resource: '*'
                    }
                }
            })]
        })
    }

    /**
     * Creates the AppSync DataSource CFN Spec pointing at the provided RDS Cluster
     * @param iamRoleLogicalID
     */
    private makeRelationalDataSource(iamRoleLogicalID: string): DataSource {
        return new DataSource ({
            Type: 'RELATIONAL_DATABASE',
            Name: `${this.context.rdsClusterIdentifier}-DataSource`,
            Description: `RDS Data Source Provisioned for ${this.context.rdsClusterIdentifier}`,
            ApiId: Fn.GetAtt(ResourceConstants.RESOURCES.GraphQLAPILogicalID, 'ApiId'),
            ServiceRoleArn: Fn.GetAtt(iamRoleLogicalID, 'Arn'),
            RelationalDatabaseConfig: {
                RelationalDatabaseSourceType: 'RDS_HTTP_ENDPOINT',
                RdsHttpEndpointConfig: {
                    AwsRegion: this.context.region,
                    DbClusterIdentifier: this.context.rdsClusterIdentifier,
                    DatabaseName: this.context.databaseName,
                    Schema: this.context.databaseSchema,
                    AwsSecretStoreArn: this.context.secretStoreArn
                }
            }
        })
    }

    /**
     * Outputs
     */
    private makeAPIKeyOutput(): Output {
        return {
            Value: Fn.GetAtt(ResourceConstants.RESOURCES.APIKeyLogicalID, 'ApiKey'),
            Export: {
                Name: Fn.Join(':', [Refs.StackName, "AppSyncApiKey"])
            }
        }
    }

    private makeGraphQLApiIdOutput(): Output {
        return {
            Value: Fn.GetAtt(ResourceConstants.RESOURCES.GraphQLAPILogicalID, 'ApiId'),
            Export: {
                Name: Fn.Join(':', [Refs.StackName, "AppSyncApiId"])
            }
        }
    }

    private makeGraphQLApiEndpointOutput(): Output {
        return {
            Value: Fn.GetAtt(ResourceConstants.RESOURCES.GraphQLAPILogicalID, 'GraphQLUrl'),
            Export: {
                Name: Fn.Join(':', [Refs.StackName, "AppSyncApiEndpoint"])
            }
        }
    }
}