/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:4ea514e6-bc16-4990-a5ea-cefe84c3050d',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_R1pdziFVe',
  aws_user_pools_web_client_id: '6am6ldh23n8ke819nuvk51cddq',
  oauth: {},
  aws_cognito_username_attributes: ['EMAIL'],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  geo: {
    amazon_location_service: {
      region: 'us-east-1',
      maps: {
        items: {
          'storeLocatorMap-main': {
            style: 'VectorEsriStreets',
          },
        },
        default: 'storeLocatorMap-main',
      },
      search_indices: {
        items: ['storeLocatorSearch-main'],
        default: 'storeLocatorSearch-main',
      },
      geofenceCollections: {
        items: ['storeLocatorGeofence-main'],
        default: 'storeLocatorGeofence-main',
      },
    },
  },
};

export default awsmobile;
