import DBSecurityGroupIngress from './dbSecurityGroupIngress';
import DBCluster from './dbCluster';
import DBSubnetGroup from './dbSubnetGroup';
import OptionGroup from './optionGroup';
import DBParameterGroup from './dbParameterGroup';
import EventSubscription from './eventSubscription';
import DBInstance from './dbInstance';
import DBSecurityGroup from './dbSecurityGroup';
import DBClusterParameterGroup from './dbClusterParameterGroup';
declare const _default: {
    DBSecurityGroupIngress: typeof DBSecurityGroupIngress;
    DBCluster: typeof DBCluster;
    DBSubnetGroup: typeof DBSubnetGroup;
    OptionGroup: typeof OptionGroup;
    DBParameterGroup: typeof DBParameterGroup;
    EventSubscription: typeof EventSubscription;
    DBInstance: typeof DBInstance;
    DBSecurityGroup: typeof DBSecurityGroup;
    DBClusterParameterGroup: typeof DBClusterParameterGroup;
};
export default _default;
