module.exports = {
  AmplifyCLIDirName: 'amplify',
  DotAmplifyDirName: '.amplify',
  DotConfigamplifyCLISubDirName: '.config',
  BackendamplifyCLISubDirName: 'backend',
  CurrentCloudBackendamplifyCLISubDirName: '#current-cloud-backend',
  PluginConfigFileName: 'plugin-config.json',
  ProjectConfigFileName: 'project-config.json',
  amplifyMetaFileName: 'amplify-meta.json',
  BrandName: 'Amplify Framework',
  CliName: 'amplify',
  DateTimeFormatString: 'YYYY-MM-DD-HH-mm-ss',
  DateTimeFormatStringCompact: 'YYYYMMDDHHmmss',
  DefaultAWSAccessKeyId: '<YOUR_ACCESS_KEY_ID>',
  DefaultAWSSecretAccessKey: '<YOUR_SECRET_ACCESS_KEY>',
  DefaultAWSRegion: 'us-east-1',
  LocalEnvFileName: 'local-env-info.json',
  ProviderInfoFileName: 'team-provider-info.json',
  BackendConfigFileName: 'backend-config.json',
  PROJECT_CONFIG_VERSION: '2.0',
};
