version: "3.8"
services:
  express:
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - public
      - private
  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    networks:
      - public
      - private
    ports:
      - "5000:5000"
networks:
  public:
  private: