export const migrationFromV4_28_2Tests = ['src/__tests__/migration_tests/lambda-layer-migration/layer-migration.test.ts'];
export const migrationFromV4_52_0Tests = ['src/__tests__/migration_tests/lambda-layer-migration/layer-migration.test.ts'];
export const migrationFromV5Tests = [
  'src/__tests__/migration_tests/notifications-migration/notifications-migration-2.test.ts',
  'src/__tests__/migration_tests/notifications-migration/notifications-migration-3.test.ts',
  'src/__tests__/migration_tests/notifications-migration/notifications-migration-4.test.ts',
  'src/__tests__/migration_tests/notifications-migration/notifications-migration.test.ts',
  'src/__tests__/migration_tests/transformer_migration/api.key.migration-2.test.ts',
  'src/__tests__/migration_tests/transformer_migration/api.key.migration.test.ts',
  'src/__tests__/update_tests/api_migration_update.test.ts',
  'src/__tests__/update_tests/auth_migration_update.test.ts',
  'src/__tests__/update_tests/function_migration_update.test.ts',
  'src/__tests__/update_tests/storage_migration_update.test.ts',
];
export const migrationFromV6Tests = [
  'src/__tests__/migration_tests/notifications-migration/notifications-migration-2.test.ts',
  'src/__tests__/migration_tests/notifications-migration/notifications-migration-3.test.ts',
  'src/__tests__/migration_tests/notifications-migration/notifications-migration-4.test.ts',
  'src/__tests__/migration_tests/notifications-migration/notifications-migration.test.ts',
  'src/__tests__/migration_tests/overrides/api-migration-a.test.ts',
  'src/__tests__/migration_tests/overrides/api-migration-b.test.ts',
  'src/__tests__/migration_tests/overrides/api-migration-c.test.ts',
  'src/__tests__/migration_tests/overrides/api-migration-d.test.ts',
  'src/__tests__/migration_tests/overrides/apigw-ext-migration.test.ts',
  'src/__tests__/migration_tests/overrides/auth-migration-a.test.ts',
  'src/__tests__/migration_tests/overrides/auth-migration-b.test.ts',
  'src/__tests__/migration_tests/overrides/auth-migration-c.test.ts',
  'src/__tests__/migration_tests/overrides/auth-migration-d.test.ts',
  'src/__tests__/migration_tests/overrides/auth-migration-e.test.ts',
  'src/__tests__/migration_tests/overrides/init-migration.test.ts',
  'src/__tests__/migration_tests/transformer_migration/api.key.migration-2.test.ts',
  'src/__tests__/migration_tests/transformer_migration/api.key.migration.test.ts',
  'src/__tests__/update_tests/api_migration_update.test.ts',
  'src/__tests__/update_tests/auth_migration_update.test.ts',
  'src/__tests__/update_tests/function_migration_update.test.ts',
  'src/__tests__/update_tests/storage_migration_update.test.ts',
];

export const migrationFromV10Tests = [
    "src/__tests__/migration_tests_v10/api-graphql-v2.migration.test.ts",
    "src/__tests__/migration_tests_v10/api-rest-basic.migration.test.ts",
    "src/__tests__/migration_tests_v10/api-rest-lambda.migration.test.ts",
    "src/__tests__/migration_tests_v10/api-rest-serverless.migration.test.ts",
    "src/__tests__/migration_tests_v10/auth-add-all.migration.test.ts",
    "src/__tests__/migration_tests_v10/auth-override.migration.test.ts",
    "src/__tests__/migration_tests_v10/custom-stack.migration.test.ts",
    "src/__tests__/migration_tests_v10/dotnet_runtime_update_migration.test.ts",
    'src/__tests__/migration_tests_v10/git-clone-migration-tests.test.ts',
    "src/__tests__/migration_tests_v10/geo.migration.test.ts",
    "src/__tests__/migration_tests_v10/scaffold.test.ts",
    "src/__tests__/migration_tests_v10/storage.migration.test.ts",
]
