module.exports = {
  AwsmobileCLIDirName: 'awsmobile',
  DotConfigAwsmobileCLISubDirName: '.config',
  BackendAwsmobileCLISubDirName: 'backend',
  CurrentCloudBackendAwsmobileCLISubDirName: '#current-cloud-backend',
  PluginConfigFileName: 'plugin-config.json',
  ProjectConfigFileName: 'project-config.json',
  AwsMobileMetaFileName: 'awsmobile-meta.json',
  BrandName: 'AWS Mobile',
  CliName: 'awsmobile',
  DateTimeFormatString: 'YYYY-MM-DD-HH-mm-ss',
  DateTimeFormatStringCompact: 'YYYYMMDDHHmmss',
  DefaultAWSAccessKeyId: '<YOUR_ACCESS_KEY_ID>',
  DefaultAWSSecretAccessKey: '<YOUR_SECRET_ACCESS_KEY>',
  DefaultAWSRegion: 'us-east-1',
};
