name: Smoke Tests

# This is required by aws-actions/configure-aws-credentials
permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: 'macos,ubuntu,windows'
      versions:
        required: false
        type: string
        default: '["rc", "latest"]'

env:
  NODE_OPTIONS: --max-old-space-size=8096

jobs:
  compute-matrix:
    outputs:
      os-list: ${{ steps.compute-os-list.outputs.os-list }}
    steps:
      - id: compute-os-list
        run: |
          os_list='${{ inputs.os }}'
          selected_runners=''
          if [[ $os_list =~ "macos" ]]; then
            selected_runners='macos-latest-xl,'
          fi
          if [[ $os_list =~ "ubuntu" ]]; then
            selected_runners="$(selected_runners)ubuntu-latest,"
          fi
          if [[ $os_list =~ "windows" ]]; then
            selected_runners="$(selected_runners)amplify-cli_windows-latest_8-core,"
          fi
          echo "os-list=$selected_runners" >> $GITHUB_OUTPUT

  run-smoke-tests:
    strategy:
      fail-fast: false
      matrix:
        os: ${{ needs.compute-matrix.outputs.os-list }}
        cli-version: ${{ fromJson(inputs.versions) }}
    name: Smoke Tests ${{ matrix.os }} ${{ matrix.cli-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          persist-credentials: false

      - name: Install Amplify CLI
        uses: ./.github/actions/install-cli
        with:
          cli-version: ${{ matrix.cli-version }}

      - name: Run Smoke Tests
        uses: ./.github/actions/run-smoke-tests
        with:
          role-to-assume: ${{ secrets.SMOKE_TESTS_ROLE_ARN }}
