name: Smoke Tests - Manual Run

# This is required by aws-actions/configure-aws-credentials
permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      os:
        required: false
        type: string
        default: 'macos,ubuntu,windows'
      versions:
        required: false
        type: string
        default: '["rc", "latest"]'

jobs:
  call-smoke-tests:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/smoke-tests.yml
    secrets: inherit
    with:
      os: ${{ github.event.inputs.os }}
      versions: ${{ github.event.inputs.versions }}
