export const CDK_DEPLOYMENT_NAME = 'AWS CDK';
export const CFN_DEPLOYMENT_NAME = 'AWS CloudFormation';
export const customDeploymentOptions = [CDK_DEPLOYMENT_NAME, CFN_DEPLOYMENT_NAME];
export const categoryName = 'custom';
export const CDK_SERVICE_NAME = 'customCDK';
export const CFN_SERVICE_NAME = 'customCloudformation';
export const DEPLOYMENT_PROVIDER_NAME = 'awscloudformation';
export const customResourceCFNFilename = `cloudformation-template.json`;
export const cdkFileName = 'cdk-stack.ts';
